services:
  backend:
    build:
      context: ./backend/src
      dockerfile: Dockerfile
    container_name: task_app_backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
     

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task_app_frontend
    ports:
      - 3000:3000
    volumes:  
      - ./frontend:/app
    # depends_on:
    #   - backend

